host:       localhost
port:       10101
min_ratio:  0.01
max_ratio:  0.05
start_test: 0
total:      1000
parts:      5
mode: bit_flip
fuzzers:
    - fuzzer:    MutatedClient
      target:    tlsplaintext
      mode:      byte_flip
      min_ratio: 0.01
      max_ratio: 0.09
    - fuzzer:    MutatedClient
      target:    tlsplaintext
      mode:      bit_flip
    - fuzzer:    MutatedClient
      target:    handshake
      mode:      byte_flip
    - fuzzer:    MutatedClient
      target:    handshake
      mode:      bit_flip
