host:       localhost
port:       10101
min_ratio:  0.01
max_ratio:  0.05
start_test: 0
total:      1000
parts:      5
mode:       bit_flip
fuzzers:
    - fuzzer:    MutatedClient
      target:    client_hello
      mode:      byte_flip
    - fuzzer:    MutatedClient
      target:    client_hello
      mode:      bit_flip
    - fuzzer:    MutatedClient
      target:    tls_plaintext
      mode:      byte_flip
      min_ratio: 0.01
      max_ratio: 0.09
      total:     500
      parts:     5
    - fuzzer:    MutatedClient
      target:    tls_plaintext
      mode:      bit_flip
      total:     500
      parts:     5
    - fuzzer:    MutatedClient
      target:    handshake
      mode:      byte_flip
      total:     500
      parts:     5
    - fuzzer:    MutatedClient
      target:    handshake
      mode:      bit_flip
      total:     500
      parts:     5
